spring.application.name=carreview
# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/carreview
spring.datasource.username=pedro
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG