spring.application.name=carreview

# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/carreview
spring.datasource.username=pedro
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true